### ISSUE TITLE
Background color missing when --no-paginate set

### ISSUE THREAD

**Issue by mrtoner** [plessl/wkpdf#41]
Odd. If `-no-paginate` is set, background colors will not be displayed. For example, this command:

```
wkpdf --output website-preview.pdf --source file:///Users/bla/Desktop/test.html --paper letter --no-paginate --margins 0 --caching no --print-background --ignore-http-errors
```

with this as the source file:

```
<html>
<head>
</head>
<body>
<div style="background-color: grey">
This<br />
is<br />
a<br />
test
</div>
</body>
</html>
```

will produce a PDF with no grey background. (There also appears to be a font size issue.)

**Comment by plessl** [comment]
Hi Don

First of all, your HTML does not validate correctly. In this case it probably doesn't matter, but I would generally recommend to feed wkpdf only HTML that validates correctly (i.e. with correct DOCTYPE and character set specification).

I assume that the problem you are seeing is related to the fact that the document width is not defined when no pagination is used and your `<div>` doesn't have a width set. I'm not sure whether this is the expected behavior of your HTML/CSS or whether this is a bug in WebKit.

But if you use the following HTML the result renders just fine:

``` HTML
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <title>untitled</title>

</head>

<body>
  <p style="background-color: grey; width: 200px;">
  This<br />
  is<br />
  a<br />
  test
  </p>
</body>
</html>
```

One more thing: `--no-paginate` does not work at least on my machine, but you need to use `--paginate no` to suppress pagination.

Hope this helps.

**Comment by mrtoner** [comment]
Odd. If I remove the `width` declaration in your example Safari will display the background color, but when I then preview the page as a PDF ( **File > Print… > PDF > Open PDF in Preview** ) the background color is not displayed.

BTW, as noted elsewhere, `--paginate no` doesn't work on my machine.

**Comment by plessl** [comment]
Your test seems to confirm my theory, that a `<div>`element without a width will be treated as zero width by the PDF renderer, but as non-zero width in the WebView that is used by Safari. I'm not sure whether this should be considered a bug in WebKit/Cocoa.

I think assigning a default width could be a workable workaround. But what about filing a bug report with WebKit?
